const vocabulary = [
    { term: "en sommarjobbare, sommarjobbaren, sommarjobbare, sommarjobbarna", translation: "kesätyöntekijä" },
    { term: "berätta, berättar, berättade, berättat", translation: "kertoa" },
    { term: "ungdomar, ungdomarna", translation: "nuoret" },
    { term: "sommarjobba, sommarjobbar, sommarjobbade, sommarjobbat", translation: "tehdä kesätöitä" },
    { term: "eftersom", translation: "koska" },
    { term: "lite", translation: "vähän, hieman" },
    { term: "tjäna, tjänar, tjänade, tjänat", translation: "tienata, ansaita rahaa" },
    { term: "arbetsliv, arbetslivet", translation: "työelämä" },
    { term: "här", translation: "tässä, täällä" },
    { term: "få, får, fick, fått", translation: "saada" },
    { term: "ett sommarjobb, sommarjobbet, sommarjobben", translation: "kesätyö" },
    { term: "som hästskötare", translation: "hevostenhoitajana" },
    { term: "utanför Gotland", translation: "Gotlannin edustalla" },
    { term: "rida, rider, red, ridit", translation: "ratsastaa" },
    { term: "ett stall, stallet, stall, stallen", translation: "talli" },
    { term: "liten, litet, lilla, små", translation: "pieni" },
    { term: "fin, fint, fina", translation: "hieno" },
    { term: "en bild, bilden, bilder, bilderna", translation: "kuva" },
    { term: "följa, följer, följde, följt", translation: "seurata" },
    { term: "skicka, skickar, skickade, skickat", translation: "lähettää" },
    { term: "ett meddelande, meddelandet, meddelanden, meddelandena", translation: "viesti" },
    { term: "en stallägare, stallägaren, stallägarna", translation: "tallinomistaja" },
    { term: "kanske", translation: "ehkä" },
    { term: "i sommar", translation: "tänä kesänä" },
    { term: "hjälpa, hjälper, hjälpte, hjälpt", translation: "auttaa, autella" },
    { term: "allt möjligt", translation: "kaikkea mahdollista" },
    { term: "söka, söker, sökte, sökt", translation: "etsiä, hakea" },
    { term: "en annons, annonsen, annonser, annonserna", translation: "ilmoitus, mainos" },
    { term: "skärgård, skärgården", translation: "saaristo" },
    { term: "där", translation: "siellä" },
    { term: "se, ser, såg, sett", translation: "nähdä" },
    { term: "så", translation: "joten" },
    { term: "ta, tar, tog, tagit", translation: "ottaa mukaan" },
    { term: "mest", translation: "eniten, enimmäkseen" },
    { term: "överlycklig, överlyckligt, överlyckliga", translation: "ikionnellinen" },
    { term: "alldeles", translation: "aivan, täysin" },
    { term: "ännu", translation: "vielä" },
    { term: "gärna", translation: "mielellään" },
    { term: "de", translation: "he, ne" },
    { term: "Glad påsk!", translation: "Hyvää pääsiäistä!" },
    { term: "senare", translation: "myöhemmin" },
    { term: "en månad, månaden, månader, månaderna", translation: "kuukausi" },
    { term: "jag skulle få jobbet", translation: "saisin työn" },
    { term: "glada hälsningar", translation: "iloiset terveiset" },
    { term: "alltid", translation: "aina" },
    { term: "Det är bra stämning där.", translation: "Siellä on hyvä tunnelma." },
    { term: "information, informationen om", translation: "tieto, informaatio jostakin" },
    { term: "ett ställe, stället, ställen, ställena", translation: "paikka" },
    { term: "varför just jag?", translation: "miksi juuri minä?" },
    { term: "skulle vara bra för jobbet", translation: "olisi hyvä työhön" },
    { term: "jobba med andra människor", translation: "työskennellä muiden ihmisten kanssa" },
    { term: "ganska snabbt", translation: "melko nopeasti" },
    { term: "ett svar, svaret, svar, svaren", translation: "vastaus" },
    { term: "väldigt hektiskt", translation: "erittäin kiireistä" },
    { term: "en jobbarkompis, jobbarkompisen, jobbarkompisar, jobbarkompisarna", translation: "työkaveri" },
    { term: "se ut, ser ut, såg ut, sett ut", translation: "näyttää joltakin" },
    { term: "jobba, jobbar, jobbade, jobbat i en butik", translation: "työskennellä kaupassa" },
    { term: "jobba på ett kafé", translation: "työskennellä kahvilassa" },
    { term: "jobba i för staden/kommunen", translation: "työskennellä kaupungille/kunnalle" },
    { term: "jobba på en byggarbetsplats", translation: "työskennellä rakennustyömaalla" },
    { term: "jobba som hjälpledare", translation: "työskennellä apuohjaajana" },
    { term: "jobba som tränare", translation: "työskennellä valmentajana" },
    { term: "sköta, sköter, kötte, skött djur", translation: "hoitaa eläimiä" },
    { term: "vara, är, var, varit barnvakt", translation: "olla lapsenvahtina" },
    { term: "vara kattvakt/hundvakt", translation: "olla kissavahtina/koiravahtina" },
    { term: "städa, städar, städade, städat", translation: "siivota" },
    { term: "sälja, säljer, sålde, sålt jordgubbar", translation: "myydä mansikoita" },
    { term: "sälja glass", translation: "myydä jäätelöä" }
];
